// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/publication-shop/app/book/internal/data/ent/publisher"
)

// PublisherCreate is the builder for creating a Publisher entity.
type PublisherCreate struct {
	config
	mutation *PublisherMutation
	hooks    []Hook
}

// SetPublisherName sets the "publisher_name" field.
func (pc *PublisherCreate) SetPublisherName(s string) *PublisherCreate {
	pc.mutation.SetPublisherName(s)
	return pc
}

// SetPublisherAddress sets the "publisher_address" field.
func (pc *PublisherCreate) SetPublisherAddress(s string) *PublisherCreate {
	pc.mutation.SetPublisherAddress(s)
	return pc
}

// SetNillablePublisherAddress sets the "publisher_address" field if the given value is not nil.
func (pc *PublisherCreate) SetNillablePublisherAddress(s *string) *PublisherCreate {
	if s != nil {
		pc.SetPublisherAddress(*s)
	}
	return pc
}

// SetPublisherPhone sets the "publisher_phone" field.
func (pc *PublisherCreate) SetPublisherPhone(s string) *PublisherCreate {
	pc.mutation.SetPublisherPhone(s)
	return pc
}

// SetNillablePublisherPhone sets the "publisher_phone" field if the given value is not nil.
func (pc *PublisherCreate) SetNillablePublisherPhone(s *string) *PublisherCreate {
	if s != nil {
		pc.SetPublisherPhone(*s)
	}
	return pc
}

// SetPublisherEmail sets the "publisher_email" field.
func (pc *PublisherCreate) SetPublisherEmail(s string) *PublisherCreate {
	pc.mutation.SetPublisherEmail(s)
	return pc
}

// SetNillablePublisherEmail sets the "publisher_email" field if the given value is not nil.
func (pc *PublisherCreate) SetNillablePublisherEmail(s *string) *PublisherCreate {
	if s != nil {
		pc.SetPublisherEmail(*s)
	}
	return pc
}

// SetPublisherWebsite sets the "publisher_website" field.
func (pc *PublisherCreate) SetPublisherWebsite(s string) *PublisherCreate {
	pc.mutation.SetPublisherWebsite(s)
	return pc
}

// SetNillablePublisherWebsite sets the "publisher_website" field if the given value is not nil.
func (pc *PublisherCreate) SetNillablePublisherWebsite(s *string) *PublisherCreate {
	if s != nil {
		pc.SetPublisherWebsite(*s)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PublisherCreate) SetID(i int) *PublisherCreate {
	pc.mutation.SetID(i)
	return pc
}

// Mutation returns the PublisherMutation object of the builder.
func (pc *PublisherCreate) Mutation() *PublisherMutation {
	return pc.mutation
}

// Save creates the Publisher in the database.
func (pc *PublisherCreate) Save(ctx context.Context) (*Publisher, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PublisherCreate) SaveX(ctx context.Context) *Publisher {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PublisherCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PublisherCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PublisherCreate) check() error {
	if _, ok := pc.mutation.PublisherName(); !ok {
		return &ValidationError{Name: "publisher_name", err: errors.New(`ent: missing required field "Publisher.publisher_name"`)}
	}
	return nil
}

func (pc *PublisherCreate) sqlSave(ctx context.Context) (*Publisher, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PublisherCreate) createSpec() (*Publisher, *sqlgraph.CreateSpec) {
	var (
		_node = &Publisher{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(publisher.Table, sqlgraph.NewFieldSpec(publisher.FieldID, field.TypeInt))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.PublisherName(); ok {
		_spec.SetField(publisher.FieldPublisherName, field.TypeString, value)
		_node.PublisherName = value
	}
	if value, ok := pc.mutation.PublisherAddress(); ok {
		_spec.SetField(publisher.FieldPublisherAddress, field.TypeString, value)
		_node.PublisherAddress = value
	}
	if value, ok := pc.mutation.PublisherPhone(); ok {
		_spec.SetField(publisher.FieldPublisherPhone, field.TypeString, value)
		_node.PublisherPhone = value
	}
	if value, ok := pc.mutation.PublisherEmail(); ok {
		_spec.SetField(publisher.FieldPublisherEmail, field.TypeString, value)
		_node.PublisherEmail = value
	}
	if value, ok := pc.mutation.PublisherWebsite(); ok {
		_spec.SetField(publisher.FieldPublisherWebsite, field.TypeString, value)
		_node.PublisherWebsite = value
	}
	return _node, _spec
}

// PublisherCreateBulk is the builder for creating many Publisher entities in bulk.
type PublisherCreateBulk struct {
	config
	err      error
	builders []*PublisherCreate
}

// Save creates the Publisher entities in the database.
func (pcb *PublisherCreateBulk) Save(ctx context.Context) ([]*Publisher, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Publisher, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PublisherMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PublisherCreateBulk) SaveX(ctx context.Context) []*Publisher {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PublisherCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PublisherCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
