// Code generated by ent, DO NOT EDIT.

package bookdetail

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the bookdetail type in the database.
	Label = "book_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "detail_id"
	// FieldIsbn holds the string denoting the isbn field in the database.
	FieldIsbn = "isbn"
	// FieldDetailHTML holds the string denoting the detail_html field in the database.
	FieldDetailHTML = "detail_html"
	// FieldDetailImg holds the string denoting the detail_img field in the database.
	FieldDetailImg = "detail_img"
	// FieldBookID holds the string denoting the book_id field in the database.
	FieldBookID = "book_id"
	// Table holds the table name of the bookdetail in the database.
	Table = "book_details"
)

// Columns holds all SQL columns for bookdetail fields.
var Columns = []string{
	FieldID,
	FieldIsbn,
	FieldDetailHTML,
	FieldDetailImg,
	FieldBookID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the BookDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIsbn orders the results by the isbn field.
func ByIsbn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsbn, opts...).ToFunc()
}

// ByDetailHTML orders the results by the detail_html field.
func ByDetailHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetailHTML, opts...).ToFunc()
}

// ByDetailImg orders the results by the detail_img field.
func ByDetailImg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetailImg, opts...).ToFunc()
}

// ByBookID orders the results by the book_id field.
func ByBookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookID, opts...).ToFunc()
}
