// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type BookDetail struct {
	ent.Schema
}

func (BookDetail) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("详情ID").StorageKey("detail_id"), field.String("isbn").Comment("国际标准书号"), field.String("detail_html").Optional().Comment("详情"), field.String("detail_img").Optional().Comment("详情"), field.Int("book_id").Optional().Comment("出版物ID")}
}
func (BookDetail) Edges() []ent.Edge {
	return nil
}
func (BookDetail) Annotations() []schema.Annotation {
	return nil
}
