// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Language struct {
	ent.Schema
}

func (Language) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("出版物语言ID").StorageKey("language_id"), field.String("language_name").Optional().Comment("出版物语言名称"), field.String("language_code").Optional()}
}
func (Language) Edges() []ent.Edge {
	return nil
}
func (Language) Annotations() []schema.Annotation {
	return nil
}
