// Code generated by ent, DO NOT EDIT.

package publisher

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the publisher type in the database.
	Label = "publisher"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "publisher_id"
	// FieldPublisherName holds the string denoting the publisher_name field in the database.
	FieldPublisherName = "publisher_name"
	// FieldPublisherAddress holds the string denoting the publisher_address field in the database.
	FieldPublisherAddress = "publisher_address"
	// FieldPublisherPhone holds the string denoting the publisher_phone field in the database.
	FieldPublisherPhone = "publisher_phone"
	// FieldPublisherEmail holds the string denoting the publisher_email field in the database.
	FieldPublisherEmail = "publisher_email"
	// FieldPublisherWebsite holds the string denoting the publisher_website field in the database.
	FieldPublisherWebsite = "publisher_website"
	// Table holds the table name of the publisher in the database.
	Table = "publishers"
)

// Columns holds all SQL columns for publisher fields.
var Columns = []string{
	FieldID,
	FieldPublisherName,
	FieldPublisherAddress,
	FieldPublisherPhone,
	FieldPublisherEmail,
	FieldPublisherWebsite,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Publisher queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublisherName orders the results by the publisher_name field.
func ByPublisherName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisherName, opts...).ToFunc()
}

// ByPublisherAddress orders the results by the publisher_address field.
func ByPublisherAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisherAddress, opts...).ToFunc()
}

// ByPublisherPhone orders the results by the publisher_phone field.
func ByPublisherPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisherPhone, opts...).ToFunc()
}

// ByPublisherEmail orders the results by the publisher_email field.
func ByPublisherEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisherEmail, opts...).ToFunc()
}

// ByPublisherWebsite orders the results by the publisher_website field.
func ByPublisherWebsite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisherWebsite, opts...).ToFunc()
}
