// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/xuanyiying/publication-shop/app/transaction/internal/biz"
	"github.com/xuanyiying/publication-shop/app/transaction/internal/conf"
	"github.com/xuanyiying/publication-shop/app/transaction/internal/data"
	"github.com/xuanyiying/publication-shop/app/transaction/internal/server"
	"github.com/xuanyiying/publication-shop/app/transaction/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	txRepo := data.NewTransactionRepo(dataData, logger)
	txUsecase := biz.NewTransactionUsecase(txRepo, logger)
	txService := service.NewTransactionService(txUsecase)
	grpcServer := server.NewGRPCServer(confServer, txService, logger)
	httpServer := server.NewHTTPServer(confServer, txService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
