// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/publication-shop/app/catalog/ent/publicationstock"
)

// PublicationStockCreate is the builder for creating a PublicationStock entity.
type PublicationStockCreate struct {
	config
	mutation *PublicationStockMutation
	hooks    []Hook
}

// SetIsbn sets the "isbn" field.
func (psc *PublicationStockCreate) SetIsbn(s string) *PublicationStockCreate {
	psc.mutation.SetIsbn(s)
	return psc
}

// SetQuantity sets the "quantity" field.
func (psc *PublicationStockCreate) SetQuantity(i int) *PublicationStockCreate {
	psc.mutation.SetQuantity(i)
	return psc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (psc *PublicationStockCreate) SetNillableQuantity(i *int) *PublicationStockCreate {
	if i != nil {
		psc.SetQuantity(*i)
	}
	return psc
}

// SetPublicationID sets the "publication_id" field.
func (psc *PublicationStockCreate) SetPublicationID(i int) *PublicationStockCreate {
	psc.mutation.SetPublicationID(i)
	return psc
}

// SetNillablePublicationID sets the "publication_id" field if the given value is not nil.
func (psc *PublicationStockCreate) SetNillablePublicationID(i *int) *PublicationStockCreate {
	if i != nil {
		psc.SetPublicationID(*i)
	}
	return psc
}

// SetID sets the "id" field.
func (psc *PublicationStockCreate) SetID(i int) *PublicationStockCreate {
	psc.mutation.SetID(i)
	return psc
}

// Mutation returns the PublicationStockMutation object of the builder.
func (psc *PublicationStockCreate) Mutation() *PublicationStockMutation {
	return psc.mutation
}

// Save creates the PublicationStock in the database.
func (psc *PublicationStockCreate) Save(ctx context.Context) (*PublicationStock, error) {
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *PublicationStockCreate) SaveX(ctx context.Context) *PublicationStock {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *PublicationStockCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *PublicationStockCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *PublicationStockCreate) check() error {
	if _, ok := psc.mutation.Isbn(); !ok {
		return &ValidationError{Name: "isbn", err: errors.New(`ent: missing required field "PublicationStock.isbn"`)}
	}
	return nil
}

func (psc *PublicationStockCreate) sqlSave(ctx context.Context) (*PublicationStock, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *PublicationStockCreate) createSpec() (*PublicationStock, *sqlgraph.CreateSpec) {
	var (
		_node = &PublicationStock{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(publicationstock.Table, sqlgraph.NewFieldSpec(publicationstock.FieldID, field.TypeInt))
	)
	if id, ok := psc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := psc.mutation.Isbn(); ok {
		_spec.SetField(publicationstock.FieldIsbn, field.TypeString, value)
		_node.Isbn = value
	}
	if value, ok := psc.mutation.Quantity(); ok {
		_spec.SetField(publicationstock.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := psc.mutation.PublicationID(); ok {
		_spec.SetField(publicationstock.FieldPublicationID, field.TypeInt, value)
		_node.PublicationID = value
	}
	return _node, _spec
}

// PublicationStockCreateBulk is the builder for creating many PublicationStock entities in bulk.
type PublicationStockCreateBulk struct {
	config
	err      error
	builders []*PublicationStockCreate
}

// Save creates the PublicationStock entities in the database.
func (pscb *PublicationStockCreateBulk) Save(ctx context.Context) ([]*PublicationStock, error) {
	if pscb.err != nil {
		return nil, pscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*PublicationStock, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PublicationStockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *PublicationStockCreateBulk) SaveX(ctx context.Context) []*PublicationStock {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *PublicationStockCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *PublicationStockCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
