// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/publication-shop/app/catalog/ent/predicate"
	"github.com/publication-shop/app/catalog/ent/publicationinfo"
)

// PublicationInfoQuery is the builder for querying PublicationInfo entities.
type PublicationInfoQuery struct {
	config
	ctx        *QueryContext
	order      []publicationinfo.OrderOption
	inters     []Interceptor
	predicates []predicate.PublicationInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublicationInfoQuery builder.
func (piq *PublicationInfoQuery) Where(ps ...predicate.PublicationInfo) *PublicationInfoQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *PublicationInfoQuery) Limit(limit int) *PublicationInfoQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *PublicationInfoQuery) Offset(offset int) *PublicationInfoQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *PublicationInfoQuery) Unique(unique bool) *PublicationInfoQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *PublicationInfoQuery) Order(o ...publicationinfo.OrderOption) *PublicationInfoQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// First returns the first PublicationInfo entity from the query.
// Returns a *NotFoundError when no PublicationInfo was found.
func (piq *PublicationInfoQuery) First(ctx context.Context) (*PublicationInfo, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publicationinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PublicationInfoQuery) FirstX(ctx context.Context) *PublicationInfo {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublicationInfo ID from the query.
// Returns a *NotFoundError when no PublicationInfo ID was found.
func (piq *PublicationInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publicationinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *PublicationInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublicationInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublicationInfo entity is found.
// Returns a *NotFoundError when no PublicationInfo entities are found.
func (piq *PublicationInfoQuery) Only(ctx context.Context) (*PublicationInfo, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publicationinfo.Label}
	default:
		return nil, &NotSingularError{publicationinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PublicationInfoQuery) OnlyX(ctx context.Context) *PublicationInfo {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublicationInfo ID in the query.
// Returns a *NotSingularError when more than one PublicationInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *PublicationInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publicationinfo.Label}
	default:
		err = &NotSingularError{publicationinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PublicationInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublicationInfos.
func (piq *PublicationInfoQuery) All(ctx context.Context) ([]*PublicationInfo, error) {
	ctx = setContextOp(ctx, piq.ctx, "All")
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublicationInfo, *PublicationInfoQuery]()
	return withInterceptors[[]*PublicationInfo](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *PublicationInfoQuery) AllX(ctx context.Context) []*PublicationInfo {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublicationInfo IDs.
func (piq *PublicationInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, "IDs")
	if err = piq.Select(publicationinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PublicationInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PublicationInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, "Count")
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*PublicationInfoQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PublicationInfoQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PublicationInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, "Exist")
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PublicationInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublicationInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PublicationInfoQuery) Clone() *PublicationInfoQuery {
	if piq == nil {
		return nil
	}
	return &PublicationInfoQuery{
		config:     piq.config,
		ctx:        piq.ctx.Clone(),
		order:      append([]publicationinfo.OrderOption{}, piq.order...),
		inters:     append([]Interceptor{}, piq.inters...),
		predicates: append([]predicate.PublicationInfo{}, piq.predicates...),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PublicationName string `json:"publication_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PublicationInfo.Query().
//		GroupBy(publicationinfo.FieldPublicationName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *PublicationInfoQuery) GroupBy(field string, fields ...string) *PublicationInfoGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublicationInfoGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = publicationinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PublicationName string `json:"publication_name,omitempty"`
//	}
//
//	client.PublicationInfo.Query().
//		Select(publicationinfo.FieldPublicationName).
//		Scan(ctx, &v)
func (piq *PublicationInfoQuery) Select(fields ...string) *PublicationInfoSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &PublicationInfoSelect{PublicationInfoQuery: piq}
	sbuild.label = publicationinfo.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublicationInfoSelect configured with the given aggregations.
func (piq *PublicationInfoQuery) Aggregate(fns ...AggregateFunc) *PublicationInfoSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *PublicationInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !publicationinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PublicationInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublicationInfo, error) {
	var (
		nodes = []*PublicationInfo{}
		_spec = piq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublicationInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublicationInfo{config: piq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (piq *PublicationInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PublicationInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publicationinfo.Table, publicationinfo.Columns, sqlgraph.NewFieldSpec(publicationinfo.FieldID, field.TypeInt))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicationinfo.FieldID)
		for i := range fields {
			if fields[i] != publicationinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PublicationInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(publicationinfo.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = publicationinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublicationInfoGroupBy is the group-by builder for PublicationInfo entities.
type PublicationInfoGroupBy struct {
	selector
	build *PublicationInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PublicationInfoGroupBy) Aggregate(fns ...AggregateFunc) *PublicationInfoGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *PublicationInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, "GroupBy")
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicationInfoQuery, *PublicationInfoGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *PublicationInfoGroupBy) sqlScan(ctx context.Context, root *PublicationInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublicationInfoSelect is the builder for selecting fields of PublicationInfo entities.
type PublicationInfoSelect struct {
	*PublicationInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *PublicationInfoSelect) Aggregate(fns ...AggregateFunc) *PublicationInfoSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *PublicationInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, "Select")
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicationInfoQuery, *PublicationInfoSelect](ctx, pis.PublicationInfoQuery, pis, pis.inters, v)
}

func (pis *PublicationInfoSelect) sqlScan(ctx context.Context, root *PublicationInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
