// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Author struct {
	ent.Schema
}

func (Author) Fields() []ent.Field {
	return []ent.Field{field.Int32("id").Comment("作者ID").StorageKey("author_id"), field.String("name").Comment("作者姓名"), field.String("biography").Optional().Comment("作者简介")}
}
func (Author) Edges() []ent.Edge {
	return nil
}
func (Author) Annotations() []schema.Annotation {
	return nil
}
