// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type BookXCatalog struct {
	ent.Schema
}

func (BookXCatalog) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("出版物分类关系ID").StorageKey("book_catalog_id"), field.Int("catalog_id").Comment("详情ID"), field.String("isbn").Comment("国际标准书号"), field.String("catalog_name").Optional().Comment("详情"), field.Int("book_id").Optional().Comment("出版物ID")}
}
func (BookXCatalog) Edges() []ent.Edge {
	return nil
}
func (BookXCatalog) Annotations() []schema.Annotation {
	return nil
}
