// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Catalog struct {
	ent.Schema
}

func (Catalog) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("分类ID").StorageKey("catalog_id"), field.String("catalog_code").Comment("分类编码"), field.String("catalog_name").Optional().Comment("分类名称"), field.String("parent_catalog_id").Comment("父编码")}
}
func (Catalog) Edges() []ent.Edge {
	return nil
}
func (Catalog) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "catalog"}}
}
