// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Classic struct {
	ent.Schema
}

func (Classic) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("出版物性质ID").StorageKey("classic_id"), field.String("classic_name").Optional().Comment("出版物性质名称")}
}
func (Classic) Edges() []ent.Edge {
	return nil
}
func (Classic) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "classic"}}
}
