// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xuanyiying/publication-shop/app/book/service/internal/data/ent/bookauthor"
	"github.com/xuanyiying/publication-shop/app/book/service/internal/data/ent/predicate"
)

// BookAuthorQuery is the builder for querying BookAuthor entities.
type BookAuthorQuery struct {
	config
	ctx        *QueryContext
	order      []bookauthor.OrderOption
	inters     []Interceptor
	predicates []predicate.BookAuthor
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BookAuthorQuery builder.
func (baq *BookAuthorQuery) Where(ps ...predicate.BookAuthor) *BookAuthorQuery {
	baq.predicates = append(baq.predicates, ps...)
	return baq
}

// Limit the number of records to be returned by this query.
func (baq *BookAuthorQuery) Limit(limit int) *BookAuthorQuery {
	baq.ctx.Limit = &limit
	return baq
}

// Offset to start from.
func (baq *BookAuthorQuery) Offset(offset int) *BookAuthorQuery {
	baq.ctx.Offset = &offset
	return baq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (baq *BookAuthorQuery) Unique(unique bool) *BookAuthorQuery {
	baq.ctx.Unique = &unique
	return baq
}

// Order specifies how the records should be ordered.
func (baq *BookAuthorQuery) Order(o ...bookauthor.OrderOption) *BookAuthorQuery {
	baq.order = append(baq.order, o...)
	return baq
}

// First returns the first BookAuthor entity from the query.
// Returns a *NotFoundError when no BookAuthor was found.
func (baq *BookAuthorQuery) First(ctx context.Context) (*BookAuthor, error) {
	nodes, err := baq.Limit(1).All(setContextOp(ctx, baq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bookauthor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (baq *BookAuthorQuery) FirstX(ctx context.Context) *BookAuthor {
	node, err := baq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BookAuthor ID from the query.
// Returns a *NotFoundError when no BookAuthor ID was found.
func (baq *BookAuthorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = baq.Limit(1).IDs(setContextOp(ctx, baq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bookauthor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (baq *BookAuthorQuery) FirstIDX(ctx context.Context) int {
	id, err := baq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BookAuthor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BookAuthor entity is found.
// Returns a *NotFoundError when no BookAuthor entities are found.
func (baq *BookAuthorQuery) Only(ctx context.Context) (*BookAuthor, error) {
	nodes, err := baq.Limit(2).All(setContextOp(ctx, baq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bookauthor.Label}
	default:
		return nil, &NotSingularError{bookauthor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (baq *BookAuthorQuery) OnlyX(ctx context.Context) *BookAuthor {
	node, err := baq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BookAuthor ID in the query.
// Returns a *NotSingularError when more than one BookAuthor ID is found.
// Returns a *NotFoundError when no entities are found.
func (baq *BookAuthorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = baq.Limit(2).IDs(setContextOp(ctx, baq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bookauthor.Label}
	default:
		err = &NotSingularError{bookauthor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (baq *BookAuthorQuery) OnlyIDX(ctx context.Context) int {
	id, err := baq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BookAuthors.
func (baq *BookAuthorQuery) All(ctx context.Context) ([]*BookAuthor, error) {
	ctx = setContextOp(ctx, baq.ctx, "All")
	if err := baq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BookAuthor, *BookAuthorQuery]()
	return withInterceptors[[]*BookAuthor](ctx, baq, qr, baq.inters)
}

// AllX is like All, but panics if an error occurs.
func (baq *BookAuthorQuery) AllX(ctx context.Context) []*BookAuthor {
	nodes, err := baq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BookAuthor IDs.
func (baq *BookAuthorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if baq.ctx.Unique == nil && baq.path != nil {
		baq.Unique(true)
	}
	ctx = setContextOp(ctx, baq.ctx, "IDs")
	if err = baq.Select(bookauthor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (baq *BookAuthorQuery) IDsX(ctx context.Context) []int {
	ids, err := baq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (baq *BookAuthorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, baq.ctx, "Count")
	if err := baq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, baq, querierCount[*BookAuthorQuery](), baq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (baq *BookAuthorQuery) CountX(ctx context.Context) int {
	count, err := baq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (baq *BookAuthorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, baq.ctx, "Exist")
	switch _, err := baq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (baq *BookAuthorQuery) ExistX(ctx context.Context) bool {
	exist, err := baq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BookAuthorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (baq *BookAuthorQuery) Clone() *BookAuthorQuery {
	if baq == nil {
		return nil
	}
	return &BookAuthorQuery{
		config:     baq.config,
		ctx:        baq.ctx.Clone(),
		order:      append([]bookauthor.OrderOption{}, baq.order...),
		inters:     append([]Interceptor{}, baq.inters...),
		predicates: append([]predicate.BookAuthor{}, baq.predicates...),
		// clone intermediate query.
		sql:  baq.sql.Clone(),
		path: baq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AuthorID int `json:"author_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BookAuthor.Query().
//		GroupBy(bookauthor.FieldAuthorID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (baq *BookAuthorQuery) GroupBy(field string, fields ...string) *BookAuthorGroupBy {
	baq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BookAuthorGroupBy{build: baq}
	grbuild.flds = &baq.ctx.Fields
	grbuild.label = bookauthor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AuthorID int `json:"author_id,omitempty"`
//	}
//
//	client.BookAuthor.Query().
//		Select(bookauthor.FieldAuthorID).
//		Scan(ctx, &v)
func (baq *BookAuthorQuery) Select(fields ...string) *BookAuthorSelect {
	baq.ctx.Fields = append(baq.ctx.Fields, fields...)
	sbuild := &BookAuthorSelect{BookAuthorQuery: baq}
	sbuild.label = bookauthor.Label
	sbuild.flds, sbuild.scan = &baq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BookAuthorSelect configured with the given aggregations.
func (baq *BookAuthorQuery) Aggregate(fns ...AggregateFunc) *BookAuthorSelect {
	return baq.Select().Aggregate(fns...)
}

func (baq *BookAuthorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range baq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, baq); err != nil {
				return err
			}
		}
	}
	for _, f := range baq.ctx.Fields {
		if !bookauthor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if baq.path != nil {
		prev, err := baq.path(ctx)
		if err != nil {
			return err
		}
		baq.sql = prev
	}
	return nil
}

func (baq *BookAuthorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BookAuthor, error) {
	var (
		nodes = []*BookAuthor{}
		_spec = baq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BookAuthor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BookAuthor{config: baq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, baq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (baq *BookAuthorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := baq.querySpec()
	_spec.Node.Columns = baq.ctx.Fields
	if len(baq.ctx.Fields) > 0 {
		_spec.Unique = baq.ctx.Unique != nil && *baq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, baq.driver, _spec)
}

func (baq *BookAuthorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bookauthor.Table, bookauthor.Columns, sqlgraph.NewFieldSpec(bookauthor.FieldID, field.TypeInt))
	_spec.From = baq.sql
	if unique := baq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if baq.path != nil {
		_spec.Unique = true
	}
	if fields := baq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookauthor.FieldID)
		for i := range fields {
			if fields[i] != bookauthor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := baq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := baq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := baq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := baq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (baq *BookAuthorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(baq.driver.Dialect())
	t1 := builder.Table(bookauthor.Table)
	columns := baq.ctx.Fields
	if len(columns) == 0 {
		columns = bookauthor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if baq.sql != nil {
		selector = baq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if baq.ctx.Unique != nil && *baq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range baq.predicates {
		p(selector)
	}
	for _, p := range baq.order {
		p(selector)
	}
	if offset := baq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := baq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BookAuthorGroupBy is the group-by builder for BookAuthor entities.
type BookAuthorGroupBy struct {
	selector
	build *BookAuthorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bagb *BookAuthorGroupBy) Aggregate(fns ...AggregateFunc) *BookAuthorGroupBy {
	bagb.fns = append(bagb.fns, fns...)
	return bagb
}

// Scan applies the selector query and scans the result into the given value.
func (bagb *BookAuthorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bagb.build.ctx, "GroupBy")
	if err := bagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BookAuthorQuery, *BookAuthorGroupBy](ctx, bagb.build, bagb, bagb.build.inters, v)
}

func (bagb *BookAuthorGroupBy) sqlScan(ctx context.Context, root *BookAuthorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bagb.fns))
	for _, fn := range bagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bagb.flds)+len(bagb.fns))
		for _, f := range *bagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BookAuthorSelect is the builder for selecting fields of BookAuthor entities.
type BookAuthorSelect struct {
	*BookAuthorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bas *BookAuthorSelect) Aggregate(fns ...AggregateFunc) *BookAuthorSelect {
	bas.fns = append(bas.fns, fns...)
	return bas
}

// Scan applies the selector query and scans the result into the given value.
func (bas *BookAuthorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bas.ctx, "Select")
	if err := bas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BookAuthorQuery, *BookAuthorSelect](ctx, bas.BookAuthorQuery, bas, bas.inters, v)
}

func (bas *BookAuthorSelect) sqlScan(ctx context.Context, root *BookAuthorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bas.fns))
	for _, fn := range bas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
